export const initialGenres = [
  { name: 'Action', description: 'High energy, stunts, and exciting sequences' },
  { name: 'Adventure', description: 'Epic journeys and heroic quests' },
  { name: 'Comedy', description: 'Humorous storylines designed to make you laugh' },
  { name: 'Drama', description: 'Deep emotional narrative and character journeys' },
  { name: 'Sci-Fi', description: 'Futuristic science, space exploration, and technology' },
  { name: 'Thriller', description: 'Suspenseful plots and unexpected twists' },
  { name: 'Romance', description: 'Love stories and romantic relationships' },
  { name: 'Horror', description: 'Frightening, supernatural, and suspenseful tales' },
  { name: 'Mystery', description: 'Puzzles, detective investigations, and crime solving' },
  { name: 'Crime', description: 'Criminal underworlds and law enforcement drama' },
];

export const initialMovies = [
  {
    title: 'Cyberpunk Odyssey',
    description: 'In a neon-drenched dystopian city of 2088, a rogue cybernetic detective uncovers a conspiracy that threatens to rewrite human consciousness.',
    poster: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=600&q=80',
    backdrop: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1600&q=80',
    releaseYear: 2026,
    genres: ['Sci-Fi', 'Action', 'Thriller'],
    languages: ['English', 'Hindi'],
    type: 'movie',
    quality: '4K Ultra HD',
    rating: 9.2,
    duration: '2h 28m',
    trailerUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    watchUrl: 'https://www.netflix.com',
    downloadUrl: 'https://example.com/download/movie.mp4',
    cast: ['Alex Vance', 'Elena Rostova', 'Marcus Thorne'],
    director: 'Denis Villeneuve',
    featured: true,
    trending: true,
  },
  {
    title: 'Shadows of Varanasi',
    description: 'An ancient secret buried along the sacred ghats of Varanasi resurfaces when a mythologist discovers a hidden manuscript detailing forgotten Vedic weaponry.',
    poster: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=600&q=80',
    backdrop: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=1600&q=80',
    releaseYear: 2025,
    genres: ['Action', 'Mystery', 'Drama'],
    languages: ['Hindi', 'Tamil', 'Telugu'],
    type: 'movie',
    quality: '4K Ultra HD',
    rating: 8.9,
    duration: '2h 45m',
    trailerUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    watchUrl: 'https://www.primevideo.com',
    cast: ['Ranveer Kapoor', 'Deepika Roy', 'Prakash Raj'],
    director: 'S. S. Rajamouli',
    featured: true,
    trending: true,
  },
  {
    title: 'The Velocity Horizon',
    description: 'Underground street racers in Tokyo team up with international intelligence operatives to stop a high-tech heist on a floating maglev train.',
    poster: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=600&q=80',
    backdrop: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=1600&q=80',
    releaseYear: 2026,
    genres: ['Action', 'Thriller'],
    languages: ['English', 'Hindi'],
    type: 'movie',
    quality: '1080p Full HD',
    rating: 8.4,
    duration: '2h 10m',
    trailerUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    watchUrl: 'https://www.netflix.com',
    downloadUrl: 'https://example.com/download/movie.mp4',
    cast: ['Jake Walker', 'Kenji Takahashi', 'Mia Hansen'],
    director: 'Justin Lin',
    featured: true,
    trending: true,
  },
  {
    title: 'Raja Vikramaditya: Legend of Kings',
    description: 'An Indian historical spectacle following the legendary Emperor Vikramaditya as he defends his empire against invading northern clans.',
    poster: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&q=80',
    backdrop: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=1600&q=80',
    releaseYear: 2025,
    genres: ['Action', 'Adventure', 'Drama'],
    languages: ['Telugu', 'Hindi', 'Tamil'],
    type: 'movie',
    quality: '4K Ultra HD',
    rating: 9.1,
    duration: '3h 05m',
    trailerUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    watchUrl: 'https://www.hotstar.com',
    cast: ['Prabhas Teja', 'Anushka Shetty', 'Rana Daggubati'],
    director: 'S. S. Rajamouli',
    featured: false,
    trending: true,
  },
  {
    title: 'Quantum Paradox',
    description: 'When a particle physics experiment in Geneva splits timeline streams, a physicist must travel across parallel dimensions to save her daughter.',
    poster: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=600&q=80',
    backdrop: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1600&q=80',
    releaseYear: 2024,
    genres: ['Sci-Fi', 'Mystery'],
    languages: ['English'],
    type: 'movie',
    quality: '4K Ultra HD',
    rating: 8.8,
    duration: '2h 18m',
    trailerUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    watchUrl: 'https://www.apple.com/apple-tv-plus',
    cast: ['Jessica Chastain', 'Oscar Isaac', 'Cillian Murphy'],
    director: 'Christopher Nolan',
    featured: false,
    trending: true,
  },
  {
    title: 'Mumbai Undercover',
    description: 'A relentless Mumbai police inspector infiltrates a syndicate operating out of the docks, uncovering political betrayal at the highest levels.',
    poster: 'https://images.unsplash.com/photo-1508873696983-2df515122519?auto=format&fit=crop&w=600&q=80',
    backdrop: 'https://images.unsplash.com/photo-1508873696983-2df515122519?auto=format&fit=crop&w=1600&q=80',
    releaseYear: 2025,
    genres: ['Crime', 'Thriller', 'Action'],
    languages: ['Hindi'],
    type: 'movie',
    quality: '1080p Full HD',
    rating: 8.6,
    duration: '2h 32m',
    trailerUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    watchUrl: 'https://www.netflix.com',
    downloadUrl: 'https://example.com/download/movie.mp4',
    cast: ['Manoj Bajpayee', 'Nawazuddin Siddiqui', 'Kay Kay Menon'],
    director: 'Anurag Kashyap',
    featured: false,
    trending: false,
  },
  {
    title: 'The Last Echo of Earth',
    description: 'In deep space, a lone maintenance crew aboard a generational ship hears a radio signal originating from an allegedly destroyed Earth.',
    poster: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&w=600&q=80',
    backdrop: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&w=1600&q=80',
    releaseYear: 2026,
    genres: ['Sci-Fi', 'Drama', 'Horror'],
    languages: ['English', 'Hindi'],
    type: 'movie',
    quality: '4K Ultra HD',
    rating: 8.7,
    duration: '2h 05m',
    trailerUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    watchUrl: 'https://www.primevideo.com',
    cast: ['Michael B. Jordan', 'Florence Pugh'],
    director: 'Ridley Scott',
    featured: false,
    trending: true,
  },
  {
    title: 'Chennai Express Heist',
    description: 'A hilarious action-comedy following three quirky friends who accidentally swap suitcases with an international diamond smuggler on a train.',
    poster: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=600&q=80',
    backdrop: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=1600&q=80',
    releaseYear: 2024,
    genres: ['Comedy', 'Action'],
    languages: ['Tamil', 'Hindi', 'Telugu'],
    type: 'movie',
    quality: '1080p Full HD',
    rating: 8.1,
    duration: '2h 15m',
    trailerUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    watchUrl: 'https://www.hotstar.com',
    cast: ['Sivakarthikeyan', 'Santhanam', 'Priya Bhavani'],
    director: 'Lokesh Kanagaraj',
    featured: false,
    trending: false,
  },
  {
    title: 'Echoes of Love',
    description: 'Two musicians in Paris meet over a shared love for vinyl records, navigating distance, ambitions, and heartbreak across a decade.',
    poster: 'https://images.unsplash.com/photo-1518199266791-5375a83190b7?auto=format&fit=crop&w=600&q=80',
    backdrop: 'https://images.unsplash.com/photo-1518199266791-5375a83190b7?auto=format&fit=crop&w=1600&q=80',
    releaseYear: 2025,
    genres: ['Romance', 'Drama'],
    languages: ['English', 'Hindi'],
    type: 'movie',
    quality: '1080p Full HD',
    rating: 8.3,
    duration: '1h 55m',
    trailerUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    watchUrl: 'https://www.netflix.com',
    downloadUrl: 'https://example.com/download/movie.mp4',
    cast: ['Timothée Chalamet', 'Zendaya'],
    director: 'Damien Chazelle',
    featured: false,
    trending: false,
  },
  {
    title: 'Whispers in the Dark',
    description: 'An abandoned manor in the mist-covered Western Ghats hides a dark paranormal entity that awakens when a group of podcasters stays overnight.',
    poster: 'https://images.unsplash.com/photo-1509248961158-e54f6934749c?auto=format&fit=crop&w=600&q=80',
    backdrop: 'https://images.unsplash.com/photo-1509248961158-e54f6934749c?auto=format&fit=crop&w=1600&q=80',
    releaseYear: 2025,
    genres: ['Horror', 'Mystery', 'Thriller'],
    languages: ['Hindi', 'Tamil'],
    type: 'movie',
    quality: '1080p Full HD',
    rating: 7.9,
    duration: '1h 48m',
    trailerUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    watchUrl: 'https://www.zee5.com',
    cast: ['Rajkummar Rao', 'Triptii Dimri'],
    director: 'Vikramaditya Motwane',
    featured: false,
    trending: false,
  },
  {
    title: 'KGF Chronicles: Dawn of Gold',
    description: 'The untold prequel story of the Kolar Gold Fields showing the rise of legendary gold lords in South India.',
    poster: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=600&q=80',
    backdrop: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1600&q=80',
    releaseYear: 2026,
    genres: ['Action', 'Crime', 'Drama'],
    languages: ['Kannada', 'Hindi', 'Telugu', 'Tamil'],
    type: 'movie',
    quality: '4K Ultra HD',
    rating: 9.3,
    duration: '2h 50m',
    trailerUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    watchUrl: 'https://www.primevideo.com',
    cast: ['Yash Gowda', 'Srinidhi Shetty'],
    director: 'Prashanth Neel',
    featured: true,
    trending: true,
  },
  {
    title: 'Solaris Lockdown',
    description: 'When an orbital space prison suffers an atmospheric failure, an inmate must partner with the chief guard to escape before reentry burn.',
    poster: 'https://images.unsplash.com/photo-1447433589675-4aaa569f3e05?auto=format&fit=crop&w=600&q=80',
    backdrop: 'https://images.unsplash.com/photo-1447433589675-4aaa569f3e05?auto=format&fit=crop&w=1600&q=80',
    releaseYear: 2024,
    genres: ['Sci-Fi', 'Action'],
    languages: ['English'],
    type: 'movie',
    quality: '1080p Full HD',
    rating: 8.0,
    duration: '1h 50m',
    trailerUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    watchUrl: 'https://www.netflix.com',
    downloadUrl: 'https://example.com/download/movie.mp4',
    cast: ['Idris Elba', 'Charlize Theron'],
    director: 'George Miller',
    featured: false,
    trending: false,
  },
  {
    title: 'The Great Indian Wedding Chaos',
    description: 'When a traditional destination wedding in Udaipur gets crash-landed by three unexpected exes, hilarious family dynamics unfold.',
    poster: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=600&q=80',
    backdrop: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1600&q=80',
    releaseYear: 2025,
    genres: ['Comedy', 'Romance'],
    languages: ['Hindi'],
    type: 'movie',
    quality: '1080p Full HD',
    rating: 8.2,
    duration: '2h 12m',
    trailerUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    watchUrl: 'https://www.primevideo.com',
    cast: ['Ayushmann Khurrana', 'Kriti Sanon', 'Pankaj Tripathi'],
    director: 'Nitesh Tiwari',
    featured: false,
    trending: false,
  },
  {
    title: 'Cyber Assassin: Zero Protocol',
    description: 'A former covert agent with implanted military AI must hunt down rogue Android mercenaries in a rain-slicked Singapore.',
    poster: 'https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=600&q=80',
    backdrop: 'https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=1600&q=80',
    releaseYear: 2026,
    genres: ['Action', 'Sci-Fi', 'Thriller'],
    languages: ['English', 'Hindi'],
    type: 'movie',
    quality: '4K Ultra HD',
    rating: 8.5,
    duration: '2h 08m',
    trailerUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    watchUrl: 'https://www.netflix.com',
    downloadUrl: 'https://example.com/download/movie.mp4',
    cast: ['Keanu Reeves', 'Rinko Kikuchi'],
    director: 'Chad Stahelski',
    featured: false,
    trending: true,
  },
  {
    title: 'Desi Cyber Heist',
    description: 'A group of ethical hackers from Bengaluru uncover a banking vulnerability used to siphon billions from small farmer accounts.',
    poster: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=600&q=80',
    backdrop: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1600&q=80',
    releaseYear: 2025,
    genres: ['Thriller', 'Crime', 'Drama'],
    languages: ['Hindi', 'Kannada', 'Tamil'],
    type: 'movie',
    quality: '1080p Full HD',
    rating: 8.7,
    duration: '2h 20m',
    trailerUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    watchUrl: 'https://www.sonyLIV.com',
    cast: ['Vikrant Massey', 'Sanya Malhotra'],
    director: 'Hansal Mehta',
    featured: false,
    trending: false,
  },
  {
    title: 'The Himalayan Expedition',
    description: 'A survival story of mountaineers stranded on Mount K2 facing sub-zero temperatures and avalanche avalanches.',
    poster: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=600&q=80',
    backdrop: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1600&q=80',
    releaseYear: 2024,
    genres: ['Adventure', 'Drama'],
    languages: ['English', 'Hindi'],
    type: 'movie',
    quality: '4K Ultra HD',
    rating: 8.4,
    duration: '2h 02m',
    trailerUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    watchUrl: 'https://www.disneyplus.com',
    cast: ['Tom Hardy', 'Benedict Cumberbatch'],
    director: 'Baltasar Kormákur',
    featured: false,
    trending: false,
  },
  {
    title: 'Heartbeat of Delhi',
    description: 'A warm romantic comedy capturing four interconnected lives across Delhi metro stations, rooftop cafes, and Chandni Chowk food stalls.',
    poster: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=600&q=80',
    backdrop: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=1600&q=80',
    releaseYear: 2025,
    genres: ['Romance', 'Comedy', 'Drama'],
    languages: ['Hindi'],
    type: 'movie',
    quality: '1080p Full HD',
    rating: 8.3,
    duration: '2h 05m',
    trailerUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    watchUrl: 'https://www.netflix.com',
    downloadUrl: 'https://example.com/download/movie.mp4',
    cast: ['Kartik Aaryan', 'Kiara Advani'],
    director: 'Imtiaz Ali',
    featured: false,
    trending: false,
  },
  {
    title: 'Submarine 704: Deep Silent',
    description: 'During a cold-war escalation in international waters, an Indian naval submarine captain faces an impossible moral dilemma.',
    poster: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80',
    backdrop: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1600&q=80',
    releaseYear: 2026,
    genres: ['Action', 'Thriller', 'Drama'],
    languages: ['Hindi', 'Tamil', 'Telugu'],
    type: 'movie',
    quality: '4K Ultra HD',
    rating: 8.9,
    duration: '2h 25m',
    trailerUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    watchUrl: 'https://www.primevideo.com',
    cast: ['Vicky Kaushal', 'Kay Kay Menon'],
    director: 'Meghna Gulzar',
    featured: false,
    trending: true,
  },
  {
    title: 'The Alchemist Guild',
    description: 'In Victorian London, an secret society of alchemical scholars accidentally creates a portal allowing magical creatures into the modern world.',
    poster: 'https://images.unsplash.com/photo-1514539079130-25950c84af65?auto=format&fit=crop&w=600&q=80',
    backdrop: 'https://images.unsplash.com/photo-1514539079130-25950c84af65?auto=format&fit=crop&w=1600&q=80',
    releaseYear: 2025,
    genres: ['Adventure', 'Sci-Fi', 'Mystery'],
    languages: ['English'],
    type: 'movie',
    quality: '4K Ultra HD',
    rating: 8.5,
    duration: '2h 15m',
    trailerUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    watchUrl: 'https://www.netflix.com',
    downloadUrl: 'https://example.com/download/movie.mp4',
    cast: ['Eddie Redmayne', 'Jude Law'],
    director: 'David Yates',
    featured: false,
    trending: false,
  },
  {
    title: 'Night Nightmare',
    description: 'A psychological horror film following a insomniac night-shift doctor who starts seeing ghost patients in the hospital corridors.',
    poster: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=600&q=80',
    backdrop: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1600&q=80',
    releaseYear: 2024,
    genres: ['Horror', 'Thriller'],
    languages: ['English', 'Hindi'],
    type: 'movie',
    quality: '1080p Full HD',
    rating: 7.8,
    duration: '1h 42m',
    trailerUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    watchUrl: 'https://www.primevideo.com',
    cast: ['Toni Collette', 'Ethan Hawke'],
    director: 'Ari Aster',
    featured: false,
    trending: false,
  }
];

export const initialSeries = [
  {
    title: 'Sacred Dynasty',
    description: 'An epic crime drama series chronicling three generations of a powerful underworld syndicate controlling illegal mining empires in South Asia.',
    poster: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=600&q=80',
    backdrop: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=1600&q=80',
    releaseYear: 2026,
    genres: ['Crime', 'Drama', 'Thriller'],
    languages: ['Hindi', 'Tamil', 'Telugu', 'English'],
    quality: '4K Ultra HD',
    rating: 9.4,
    seasonsCount: 2,
    totalEpisodes: 16,
    trailerUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    cast: ['Pankaj Tripathi', 'Nawazuddin Siddiqui', 'Jaideep Ahlawat'],
    creator: 'Anurag Kashyap & Vikramaditya Motwane',
    featured: true,
    trending: true,
    seasons: [
      {
        seasonNumber: 1,
        seasonTitle: 'Season 1: Rise of Power',
        episodes: [
          { episodeNumber: 1, title: 'The Golden Oath', duration: '52m', description: 'A young heir takes over the syndicate after a betrayal.' },
          { episodeNumber: 2, title: 'Blood on the Coal', duration: '48m', description: 'Tensions rise as rival gangs push boundary limits.' },
          { episodeNumber: 3, title: 'Shadow Alliance', duration: '55m', description: 'A covert meeting with government ministers changes everything.' },
        ],
      },
      {
        seasonNumber: 2,
        seasonTitle: 'Season 2: Empire in Flames',
        episodes: [
          { episodeNumber: 1, title: 'Reckoning', duration: '54m', description: 'The syndicate faces an internal revolt.' },
          { episodeNumber: 2, title: 'The Final Gambit', duration: '60m', description: 'An all-out war consumes the city.' },
        ],
      },
    ],
  },
  {
    title: 'Cyber Net: Season Zero',
    description: 'A sci-fi thriller about a covert unit of elite hackers protecting critical quantum servers from state-sponsored cyber terror.',
    poster: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=600&q=80',
    backdrop: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1600&q=80',
    releaseYear: 2025,
    genres: ['Sci-Fi', 'Thriller', 'Action'],
    languages: ['English', 'Hindi'],
    quality: '4K Ultra HD',
    rating: 9.1,
    seasonsCount: 1,
    totalEpisodes: 8,
    trailerUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    cast: ['Rami Malek', 'Christian Slater', 'Carly Chaikin'],
    creator: 'Sam Esmail',
    featured: true,
    trending: true,
    seasons: [
      {
        seasonNumber: 1,
        seasonTitle: 'Season 1: Firewall Breach',
        episodes: [
          { episodeNumber: 1, title: 'Hello World', duration: '46m', description: 'An unexpected DDoS attack leads to a deeper anomaly.' },
          { episodeNumber: 2, title: 'Encrypted Truth', duration: '50m', description: 'The team decrypts a black-budget satellite feed.' },
        ],
      },
    ],
  },
  {
    title: 'Mirzapur Underworld: Legacy',
    description: 'The ruthless battle for power in Purvanchal reaches explosive climaxes as new contenders challenge the throne.',
    poster: 'https://images.unsplash.com/photo-1514539079130-25950c84af65?auto=format&fit=crop&w=600&q=80',
    backdrop: 'https://images.unsplash.com/photo-1514539079130-25950c84af65?auto=format&fit=crop&w=1600&q=80',
    releaseYear: 2025,
    genres: ['Action', 'Crime', 'Drama'],
    languages: ['Hindi'],
    quality: '4K Ultra HD',
    rating: 9.2,
    seasonsCount: 3,
    totalEpisodes: 24,
    trailerUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    cast: ['Ali Fazal', 'Pankaj Tripathi', 'Shweta Tripathi'],
    creator: 'Karan Anshuman',
    featured: false,
    trending: true,
    seasons: [
      {
        seasonNumber: 1,
        seasonTitle: 'Season 1: The Throne',
        episodes: [
          { episodeNumber: 1, title: 'Guddu vs Kaleen', duration: '55m', description: 'The opening moves of Purvanchal.' },
        ],
      },
    ],
  },
  {
    title: 'The Family Agent',
    description: 'A middle-class man secretly working as a senior intelligence officer balances national security threats while taking his kids to school.',
    poster: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=600&q=80',
    backdrop: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1600&q=80',
    releaseYear: 2024,
    genres: ['Action', 'Comedy', 'Drama'],
    languages: ['Hindi', 'Tamil', 'Telugu'],
    quality: '4K Ultra HD',
    rating: 9.3,
    seasonsCount: 2,
    totalEpisodes: 18,
    trailerUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    cast: ['Manoj Bajpayee', 'Priyamani', 'Sharib Hashmi'],
    creator: 'Raj & DK',
    featured: false,
    trending: true,
    seasons: [
      {
        seasonNumber: 1,
        seasonTitle: 'Season 1: Mission Zrik',
        episodes: [
          { episodeNumber: 1, title: 'The Covert Dad', duration: '49m', description: 'TKM squad receives a high priority terror alert.' },
        ],
      },
    ],
  },
  {
    title: 'Stranger Dimensions',
    description: 'When a boy vanishes in a quiet Midwestern town, his friends uncover a mystery involving secret experiments and terrifying supernatural forces.',
    poster: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=600&q=80',
    backdrop: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1600&q=80',
    releaseYear: 2025,
    genres: ['Sci-Fi', 'Horror', 'Mystery'],
    languages: ['English', 'Hindi'],
    quality: '4K Ultra HD',
    rating: 8.9,
    seasonsCount: 4,
    totalEpisodes: 34,
    trailerUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    cast: ['Millie Bobby Brown', 'Finn Wolfhard', 'Winona Ryder'],
    creator: 'Duffer Brothers',
    featured: false,
    trending: true,
  },
  {
    title: 'Delhi Crime Files',
    description: 'An immersive procedural series based on meticulous real-life criminal investigations conducted by Delhi Police officers.',
    poster: 'https://images.unsplash.com/photo-1453872302359-0f5901b84f8b?auto=format&fit=crop&w=600&q=80',
    backdrop: 'https://images.unsplash.com/photo-1453872302359-0f5901b84f8b?auto=format&fit=crop&w=1600&q=80',
    releaseYear: 2024,
    genres: ['Crime', 'Drama', 'Mystery'],
    languages: ['Hindi', 'English'],
    quality: '1080p Full HD',
    rating: 9.0,
    seasonsCount: 2,
    totalEpisodes: 12,
    trailerUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    cast: ['Shefali Shah', 'Rasika Dugal', 'Rajesh Tailang'],
    creator: 'Richie Mehta',
    featured: false,
    trending: false,
  },
  {
    title: 'Game of Kingdoms',
    description: 'Nine noble families fight for control over the mythical lands of Westeros, while an ancient enemy returns after being dormant for millennia.',
    poster: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80',
    backdrop: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1600&q=80',
    releaseYear: 2024,
    genres: ['Adventure', 'Drama', 'Action'],
    languages: ['English', 'Hindi'],
    quality: '4K Ultra HD',
    rating: 9.5,
    seasonsCount: 8,
    totalEpisodes: 73,
    trailerUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    cast: ['Emilia Clarke', 'Kit Harington', 'Peter Dinklage'],
    creator: 'David Benioff',
    featured: false,
    trending: true,
  },
  {
    title: 'The Kota Factory',
    description: 'A realistic look into the lives of IIT aspirants in Kota as they deal with academic pressure, friendships, and mentorship.',
    poster: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=600&q=80',
    backdrop: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=1600&q=80',
    releaseYear: 2024,
    genres: ['Drama', 'Comedy'],
    languages: ['Hindi'],
    quality: '1080p Full HD',
    rating: 9.1,
    seasonsCount: 3,
    totalEpisodes: 15,
    trailerUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    cast: ['Jitendra Kumar', 'Mayur More', 'Ahsaas Channa'],
    creator: 'Saurabh Khanna',
    featured: false,
    trending: false,
  },
  {
    title: 'Panchayat Tales',
    description: 'An engineering graduate reluctantly joins as a secretary of a remote Panchayat office in Uttar Pradesh, encountering eccentric villagers.',
    poster: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=600&q=80',
    backdrop: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1600&q=80',
    releaseYear: 2025,
    genres: ['Comedy', 'Drama'],
    languages: ['Hindi'],
    quality: '1080p Full HD',
    rating: 9.3,
    seasonsCount: 3,
    totalEpisodes: 24,
    trailerUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    cast: ['Jitendra Kumar', 'Raghubir Yadav', 'Neena Gupta'],
    creator: 'Chandan Kumar',
    featured: false,
    trending: true,
  },
  {
    title: 'Asura: Science vs Myth',
    description: 'A forensic officer and an expert in Indian mythology investigate a serial killer who leaves behind masks of ancient demon kings.',
    poster: 'https://images.unsplash.com/photo-1509248961158-e54f6934749c?auto=format&fit=crop&w=600&q=80',
    backdrop: 'https://images.unsplash.com/photo-1509248961158-e54f6934749c?auto=format&fit=crop&w=1600&q=80',
    releaseYear: 2025,
    genres: ['Mystery', 'Thriller', 'Crime'],
    languages: ['Hindi', 'Tamil', 'Telugu'],
    quality: '4K Ultra HD',
    rating: 9.0,
    seasonsCount: 2,
    totalEpisodes: 16,
    trailerUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    cast: ['Arshad Warsi', 'Barun Sobti'],
    creator: 'Gaurav Shukla',
    featured: false,
    trending: true,
  }
];
